### ISSUE TITLE
c2c.tensor.InteractionTensor TypeError

### ISSUE THREAD

**Issue by mabro7766** [earmingol/cell2cell#34]
Hello,

I was following the Brain_ASD  Tensor-cell2cell tutorial and ran into an error at this stage:
![image](https://github.com/earmingol/cell2cell/assets/117817607/38614a4f-09b6-4201-acc1-2aeeb3dfacd0)

I started from the Brain_ASD.h5ad file and checked the outputs generated at each step of the tutorial and they match with yours up until this point.

Cheers!

**Comment by earmingol** [comment]
which version of pandas are you using? the issue seems to be related to that since newer versions do not support passing sets as an indexer of dataframes.

I would recommend installing an older version of pandas (e.g. 1.3.5). At some point I will fix this error to make it compatible with newer versions.

**Comment by mabro7766** [comment]
Hi,

Thanks for your quick response! This indeed resolved my issue.

Cheers!
