### ISSUE TITLE
`c2c.io.read_data.load_tensor` loads NoneType

### ISSUE THREAD

**Issue by paupaiz** [earmingol/cell2cell#48]
Tensor output of `c2c.analysis.run_tensor_cell2cell_pipeline` works fine but loading it from the .pkl file doesn't
Can reproduce this error in the package's colab demo. 
<img width="907" alt="Screenshot 2023-12-22 at 6 05 59 PM" src="https://github.com/earmingol/cell2cell/assets/59720098/aa0a721b-fd74-4462-a586-e255a5e20f40">

**Comment by earmingol** [comment]
It looks like you are loading the tensor properly since it prints the InteractionTensor object. However, you get Nonetype for the `tensor.factors` and `tensor.rank`, which means you haven't run the decomposition on that object. 

It could be because you are saving the tensor before running the decomposition.

**Comment by earmingol** [comment]
Just checked the google collab and yes, the tensor you are saving is the one without running the decomposition (`tensor`). The one to save should be the variable `tensor2, which includes the outputs of running the pipeline. I have modified now the collab to save `tensor2` instead.
